// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using uk.co.edgewords.nfocuswebdriver.Utils;

namespace uk.co.edgewords.nfocuswebdriver.TestCases
{
    [TestFixture]
    public class FormsDemoTest : BaseTest
    {
        
        [Test, Category("Regression")]
        public void formsDemo()
        {
            // Test name: FormsDemo
            // Step # | name | target | value
            // 1 | open | /webdriver2/docs/index.html | 
            driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/webdriver2/docs/index.html");
            // 2 | setWindowSize | 1149x1032 | 
            //driver.Manage().Window.Size = new System.Drawing.Size(1149, 1032);
            driver.Manage().Window.Maximize(); //Cross browser maximize
            // 3 | click | css=li:nth-child(3) span | 
            driver.FindElement(By.CssSelector("li:nth-child(3) span")).Click();
            // 4 | click | id=textInput | 
            driver.FindElement(By.Id("textInput")).Click();
            // 5 | type | id=textInput | Stephen
            driver.FindElement(By.Id("textInput")).SendKeys("Steve");
            // 6 | click | id=textArea | 
            driver.FindElement(By.Id("textArea")).Click();
            // 7 | type | id=textArea | some text
            driver.FindElement(By.Id("textArea")).SendKeys("some text");
            // 8 | click | id=checkbox | 
            driver.FindElement(By.Id("checkbox")).Click();
            // 9 | click | id=select | 
            driver.FindElement(By.Id("select")).Click();
            // 10 | select | id=select | label=Selection Two
            {
                var dropdown = driver.FindElement(By.Id("select"));
                dropdown.FindElement(By.XPath("//option[. = 'Selection Two']")).Click(); //This xpath finds the inner text of the option element and selects based on that
            }

            //An alternative way to handle select drop downs using the Selenium.Support package
            var dropdownelm = driver.FindElement(By.Id("select"));
            SelectElement elm = new SelectElement(dropdownelm);
            elm.SelectByIndex(0); //select the first option elm i.e. Selection One
            elm.SelectByText("Selection One");
            IWebElement currentSelection = elm.SelectedOption;
            Console.WriteLine(currentSelection.Text);

            // 11 | click | id=three | 
            driver.FindElement(By.Id("three")).Click();
            // 12 | click | linkText=Submit | 
            driver.FindElement(By.LinkText("Submit")).Click();
            // 13 | click | css=tr:nth-child(2) > td:nth-child(3) | 
            driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(3)")).Click();
            // 14 | assertText | id=textInputValue | Steve
            Assert.That(driver.FindElement(By.Id("textInputValue")).Text, Is.EqualTo("Steve"));
            // 15 | click | linkText=Home | 
            driver.FindElement(By.LinkText("Home")).Click();
        }
    }
}